services:
  database:
    image: postgres:16.4
    container_name: database
    env_file:
      - .env
    environment:
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - D:/Codes/Database/AgendaHub/data:/var/lib/postgresql/data

  server:
    build: .
    container_name: server
    depends_on:
      - database
    ports:
      - 8000:8000
    env_file:
      - .env
